example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/memo_local"
spring.datasource.username: "memoservice"
spring.datasource.password: "{cipher}d2ae59db2a95e934e8f1a551287bb463fcd6bf3091056f34cb50128edd7033f7"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
#redis.server: "redis"
#redis.port: "6379"
#signing.key: "345345fsdfsf5345"