version: '2'
services:
  memo-config-server:
      image: templecloud/memo-config-server:0.0.1
      ports:
        - "8888:8888"
  memo-service:
      image: templecloud/memo-service:0.0.1
      ports:
        - "8080:8080"
