server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.xepsa: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# zuul route configuration
zuul:
  prefix:  /api
  # ignored-services: '*' will ignore all eureka services...
  ignored-services: 'userservice'
  routes:
    userservice: /user/**
    memoservice: /memo/**
    # static route examples
    # memo-static:
    #   path: /memo-static/**
    #   url:  http://memo-static:8081
    # google-static:
    #   path: /google-static/**
    #   url:  http://www.google.com:80